ARG NODE_VERSION=25-alpine3.22

FROM node:${NODE_VERSION} AS dev

WORKDIR /app
COPY package.json package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]